# Generated by Django 5.1.4 on 2025-01-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
