name: Django CI

on:
  push:
    pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - users: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (with poetry)
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev --sync

      - name: Runing Django tests with coverage
        run: |
          poetry run pytest app/ --cov=app --cov-config=pyproject.toml